server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aisoftoj?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: abc123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nan.aisoftoj.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 文件上传配置
file:
  upload:
    path: ./uploads/
    url-prefix: /uploads/

logging:
  level:
    com.nan.aisoftoj: debug 